events {}
http {
    server {
        listen 80;
        
        # Obsługa frontendu
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Przekierowanie do mikroserwisów
        location /api/products {
            proxy_pass http://products:3000;
        }

        location /api/orders {
            proxy_pass http://orders:3000;
            proxy_set_header Content-Type application/json;
        }
    }
}